# Usa uma imagem oficial do Node.js
FROM node:20-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependências
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos da aplicação
COPY . .

EXPOSE 8082

ENV HOST=0.0.0.0

# Comando para rodar a aplicação
CMD ["npm", "run", "dev", "--", "--host"]
